-- ==============================================================================
-- WAYA SURF BLOG - MASTER SETUP SCRIPT
-- Run this in Supabase SQL Editor to fix "Missing Table" and "Permission" errors.
-- ==============================================================================

-- 1. Create the POSTS table (This was missing!)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text not null,
  image text,
  excerpt text,
  content text,
  is_text_only boolean default false
);

-- 2. Security for POSTS Table
alter table public.posts enable row level security;

-- Allow everyone to READ posts
drop policy if exists "Enable read access for all users" on public.posts;
create policy "Enable read access for all users" on public.posts for select using (true);

-- Allow Admin (Logged in users) to WRITE posts
drop policy if exists "Enable insert access for authenticated users only" on public.posts;
create policy "Enable insert access for authenticated users only" on public.posts for insert with check (auth.role() = 'authenticated');

-- Allow Admin to UPDATE posts
drop policy if exists "Enable update access for authenticated users only" on public.posts;
create policy "Enable update access for authenticated users only"
on public.posts for update
using ( auth.role() = 'authenticated' )
with check ( auth.role() = 'authenticated' );

-- Allow Admin to DELETE posts
drop policy if exists "Enable delete access for authenticated users only" on public.posts;
create policy "Enable delete access for authenticated users only"
on public.posts for delete
using ( auth.role() = 'authenticated' );


-- 3. Security for IMAGES (Storage)
-- Allow everyone to SEE images
drop policy if exists "Give public access to news-images" on storage.objects;
create policy "Give public access to news-images" on storage.objects for select using ( bucket_id = 'news-images' );

-- Allow Admin to UPLOAD images
drop policy if exists "Allow authenticated uploads" on storage.objects;
create policy "Allow authenticated uploads" on storage.objects for insert with check ( bucket_id = 'news-images' and auth.role() = 'authenticated' );

-- Ensure the bucket exists (Just in case)
insert into storage.buckets (id, name, public)
values ('news-images', 'news-images', true)
on conflict (id) do nothing;
