-- Create the posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text not null,
  image text,
  excerpt text,
  content text,
  is_text_only boolean default false
);

-- Enable Row Level Security
alter table public.posts enable row level security;

-- Policy 1: Public Read Access (Everyone can see posts)
create policy "Enable read access for all users"
on public.posts for select
using (true);

-- Policy 2: Authenticated Insert Access (Only logged-in users can post)
create policy "Enable insert access for authenticated users only"
on public.posts for insert
with check (auth.role() = 'authenticated');

-- Note for User:
-- You must go to Authentication > Users in Supabase and create a user (email/password)
-- to log in to the Admin panel.
