-- Create table for Surfcamp Waitlist
create table surfcamp_waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table surfcamp_waitlist enable row level security;

-- Create policy to allow anyone to insert (anon)
create policy "Enable insert for everyone" on surfcamp_waitlist for insert with check (true);

-- Create policy to allow only authenticated users (admins) to select
create policy "Enable select for authenticated users only" on surfcamp_waitlist for select using (auth.role() = 'authenticated');
